### ISSUE TITLE
Test open_play_close_raw fails on macOS High Sierra (10.13.6)

### ISSUE THREAD

**Issue by maoe** [szymonwieloch/rust-dlopen#8]
`RUST_BACKTRACE=1 cargo test` fails on my laptop:

```
     Running target/debug/deps/raw-5bfffb8910e2b187

running 1 test
test open_play_close_raw ... FAILED

failures:

---- open_play_close_raw stdout ----
Library path: /Users/maoe/src/github.com/szymonwieloch/rust-dlopen/target/debug/deps/libexample.dylib.dSYM
thread 'open_play_close_raw' panicked at 'Could not open library: OpeningLibraryError(Custom { kind: Other, error: StringError("dlopen(/Users/maoe/src/github.com/szymonwieloch/rust-dlopen/target/debug/deps/libexample.dylib.dSYM, 5): no suitable image found.  Did find:\n\t/Users/maoe/src/github.com/szymonwieloch/rust-dlopen/target/debug/deps/libexample.dylib.dSYM: not a file\n\t/Users/maoe/src/github.com/szymonwieloch/rust-dlopen/target/debug/deps/libexample.dylib.dSYM: not a file\n\t/Users/maoe/src/github.com/szymonwieloch/rust-dlopen/target/debug/deps/libexample.dylib.dSYM: not a file\n\t/Users/maoe/src/github.com/szymonwieloch/rust-dlopen/target/debug/deps/libexample.dylib.dSYM: not a file") })', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: std::panicking::try::do_call
             at libstd/panicking.rs:337
   7: <T as core::any::Any>::get_type_id
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
             at /private/tmp/rust-20180803-66047-v6t750/rustc-1.28.0-src/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /private/tmp/rust-20180803-66047-v6t750/rustc-1.28.0-src/src/libcore/result.rs:809
  10: raw::open_play_close_raw
             at tests/raw.rs:16
  11: raw::__test::TESTS::{{closure}}
             at tests/raw.rs:14
  12: core::ops::function::FnOnce::call_once
             at /private/tmp/rust-20180803-66047-v6t750/rustc-1.28.0-src/src/libcore/ops/function.rs:223
  13: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /private/tmp/rust-20180803-66047-v6t750/rustc-1.28.0-src/src/libcore/ops/function.rs:223
             at /private/tmp/rust-20180803-66047-v6t750/rustc-1.28.0-src/src/liballoc/boxed.rs:640
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105


failures:
    open_play_close_raw

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test raw'
```

As the error message says `libexample.dylib.dSYM` is indeed not a file. It's a bundle which contains a shared lib.
```
% tree target/debug/deps/libexample.dylib.dSYM/                                                                  
target/debug/deps/libexample.dylib.dSYM/
└── Contents
    ├── Info.plist
    └── Resources
        └── DWARF
            └── libexample.dylib

3 directories, 2 files
% file target/debug/deps/libexample.dylib.dSYM/Contents/Resources/DWARF/libexample.dylib
target/debug/deps/libexample.dylib.dSYM/Contents/Resources/DWARF/libexample.dylib: Mach-O 64-bit dSYM companion file x86_64
```

I'm testing this with the current master with rustc 1.28.0.

**Comment by szymonwieloch** [comment]
Hi @maoe ,

I am sorry for the long delay but my mom recently had a car accident and I was unable to participate in open source projects.

Travis CI regularly tests this code on MacOs, so I am curios why this does not work on your machine. I am sure though that this is only a problem with testing, not with the core dlopen functionality. 

Anyway, I have added some changes to my testing code. Now it searches recursively for the given library. This should fix problems on your machine and it should provide forward compatibility in case Rust changes its dependency naming pattern in the future.

Could you please test this solution? I am talking about the code in the master branch, I haven't published the new version yet.

**Comment by maoe** [comment]
I'm sorry to hear that. I hope your mom is getting better soon.

I just ran cargo test on the current master and it worked fine. Thank you!

**Comment by szymonwieloch** [comment]
@maoe Great to hear that and than you for your contribution!
